### ISSUE TITLE
Parallax Title!

### ISSUE THREAD

**Issue by Techcraft7** [PiggyClone205/piggyclone205.github.io#4]
Lets do this!

[W3Schoolz](https://www.w3schools.com/howto/howto_css_parallax.asp)

**Comment by PiggyClone205** [comment]
[Here's a template, my guy.](https://codepen.io/rkoms/pen/oWazjV)

**Comment by Techcraft7** [comment]
ok what images do u want

**Comment by Techcraft7** [comment]
yeah it wont work hmmm

**Comment by Techcraft7** [comment]
Cannot be accomplished, may later be reopened.
